<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.1.0"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.1.0"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.0"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.0"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.1.0"/>
        <PackageReference Include="MySql.Data" Version="9.2.0" />
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0-preview.2.efcore.9.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Images\" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Images\Logo.png" />
      <AvaloniaResource Include="Images\Logo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Images\User.jpg" />
      <AvaloniaResource Include="Images\User.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Images\RedButton.png" />
      <AvaloniaResource Include="Images\RedButton.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </AvaloniaResource>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Todo.Entities\Todo.Entities..csproj" />
    </ItemGroup>
</Project>
